# This is the amazing constants file! This file contains data that is used by pretty much almost all other .py files
# You can treat this file very similarly to .ini files you find with many other games.
# It contains many values necessary for other modules to run correctly.

# For proper full screen, please change FULLSCREEN flag to 1 and then change the SCALE flag to match
# your monitors resolution settings.
# Windows 10's scaling feature has not been tested yet, so you may want to set it to 100% for the
# game to run properly.

# SCALE, FULLSCREEN AND FPS INFORMATION
MAX_SUPPORTED_RESOLUTION = (1920, 1080)
FULLSCREEN = 0
SCALE = 1                         # 1=(480x270), 2=(960x540), 3=(1280x720), 4=(1920x1080)
FPS = 60

# GAME NATIVE RESOLUTION INFORMATION
NATIVE_WIDTH = 480
NATIVE_HEIGHT = 270
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)
NATIVE_WIDTH_CENTER = NATIVE_WIDTH // 2
NATIVE_HEIGHT_CENTER = NATIVE_HEIGHT // 2
NATIVE_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT_CENTER)
NATIVE_TOP = 0
NATIVE_BOTTOM = NATIVE_HEIGHT
NATIVE_LEFT = 0
NATIVE_RIGHT = NATIVE_WIDTH
NATIVE_TOP_LEFT = (0, 0)
NATIVE_TOP_RIGHT = (NATIVE_WIDTH, NATIVE_TOP)
NATIVE_BOTTOM_RIGHT = NATIVE_SIZE
NATIVE_BOTTOM_LEFT = (NATIVE_LEFT, NATIVE_HEIGHT)
NATIVE_TOP_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_TOP)
NATIVE_RIGHT_CENTER = (NATIVE_WIDTH, NATIVE_HEIGHT_CENTER)
NATIVE_BOTTOM_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT)
NATIVE_LEFT_CENTER = (NATIVE_LEFT, NATIVE_HEIGHT_CENTER)

# GAME DISPLAY RESOLUTION DATA. DISPLAY RESOLUTION IS NATIVE RESOLUTION MULTIPLIED BY THE GAMES SCALING VALUE
DISPLAY_WIDTH = NATIVE_WIDTH * SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT * SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
DISPLAY_TOP_LEFT = (0, 0)

# GAME STATE INFORMATION
SPLASH_SCREEN = "SPLASH_SCREEN"
MAIN_MENU = "MAIN_MENU"
CHARACTER_SELECT = "CHARACTER_SELECT"
LEVEL_SELECT = "LEVEL_SELECT"
LEVEL = "LEVEL"
CUTSCENE = "CUTSCENE"
GAME_STATES = [SPLASH_SCREEN,
               MAIN_MENU,
               CHARACTER_SELECT,
               LEVEL_SELECT,
               LEVEL,
               CUTSCENE]
STARTING_STATE = GAME_STATES[0]

# TILE SIZE INFORMATION
SMALL_TILE_SIZE = (8, 8)
MED_TILE_SIZE = (16, 16)
LARGE_TILE_SIZE = (24, 24)
XL_TILE_SIZE = (32, 32)

# GRAPHICS COLORKEY
COLOR_KEY = (255, 0, 255)

# USER INPUT INFORMATION
UPHAT = "UPHAT"
DOWNHAT = "DOWNHAT"
LEFTHAT = "LEFTHAT"
RIGHTHAT = "RIGHTHAT"
A_BTN = "A_BTN"
B_BTN = "B_BTN"
X_BTN = "X_BTN"
Y_BTN = "Y_BTN"
LB_BTN = "LB_BTN"
RB_BTN = "RB_BTN"
LT_BTN = "LT_BTN"
RT_BTN = "RT_BTN"
START_BTN = "START_BTN"
SELECT_BTN = "SELECT_BTN"

# DIRECTORY INFORMATION
DIR_FONTS = "fonts\\"
DIR_GRAPHICS = "graphics\\"
DIR_MUSIC = "music\\"
DIR_SOUNDS = "sounds\\"
DIR_GAME_DATA = "game_data\\"